### ISSUE TITLE
Request supports for Companion Server API v1

### ISSUE THREAD

**Issue by naruko-hstk** [sedders123/vscode-ytmusic#292]
YTM Desktop will come to v2
Old api will dead
Here's new docs
https://github.com/ytmdesktop/ytmdesktop/wiki/v2-%E2%80%90-Companion-Server-API-v1

**Comment by sedders123** [comment]
👍 This is on my list, but has unfortunately kept slipping. Hoping to spend some time on this over the weekend 🤞

**Comment by AlexZeGamer** [comment]
hey I would be interested too :)

**Comment by slavko-clubee** [comment]
Hey, I'm also waiting for integration with YTM Desktop v2.
Thank you for greate tool

**Comment by sedders123** [comment]
Sorry for the delay! I have thrown together #369 which adds support for V2 using the new socket API. I'm going to run the updated extension for a day or two and if I don't get any exceptions or issues I'll merge and do a release on the marketplace.

If you'd like to help test you can download the extension from the [CI artifacts](https://github.com/sedders123/vscode-ytmusic/actions/runs/12384129133) and [install the VSIX](https://stackoverflow.com/a/50232194/5179209) and report any issues here or on the PR :)

**Comment by sedders123** [comment]
After using this for a day it seems to be working, so have released to the Marketplace as version 2.0.0. Going to close this issue as we now have support for the Companion Server but please do report any issues that may arise!

**Comment by slavko-clubee** [comment]
Thanks, I will test it later
