### ISSUE TITLE
Icon font subset upgrade for more meaningful icons

### ISSUE THREAD

**Issue by davidstoegmueller** [sedders123/vscode-ytmusic#331]
Hello @sedders123 i would like to open a PR with my lastest changes.
I've upgraded the icon font subset with more meaningful and improved icons.
Could you please give me access so i can open a PR with my changes?

Here's a screenshot of how it looks like.
![image](https://github.com/sedders123/vscode-ytmusic/assets/13696150/c38688b9-e164-448c-9ab4-f916d3fe09c3)

**Comment by sedders123** [comment]
Thanks for reaching out! You should be able to open a pull request by forking this repository and then pushing your changes to your fork :)
